I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/functions.rpy", line 149, in script call
    call write_letter # shows the full letter
  File "game/functions.rpy", line 149, in script call
    call write_letter # shows the full letter
renpy.script.LabelNotFound: could not find label 'write_letter'.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/functions.rpy", line 149, in script call
    call write_letter # shows the full letter
  File "renpy/ast.py", line 1622, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/functions.rpy", line 149, in script call
    call write_letter # shows the full letter
  File "renpy/script.py", line 1161, in lookup
    raise LabelNotFound(original)
renpy.script.LabelNotFound: could not find label 'write_letter'.

Windows-11-10.0.22631-SP0 AMD64
Ren'Py 8.4.1.25072401
Inkbound 1.0
Thu Sep 11 01:35:31 2025
